### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by benheilers** [onyx-platform/onyx-twitter-sample#2]
The readme was not updated after docker-compose.yml was removed in commit e76ef42. So it's misleading.

More generally, I came to this sample project because it's a little unclear to me whether it's best practice to run start-peers and submit-job in the same docker container or seperate. If that could be documented somewhere, that would be helpful.

**Comment by gardnervickers** [comment]
@benheilers With implementing Kubernetes support there have been some large-ish changes to the images and deploy process. Thanks for the catch I have noted that in the readme. 

As for deployment, that's up to you. I will say that I recommend only ever running one process per container.

**Comment by gardnervickers** [comment]
That said, I'm going to close this and create another issue for re-doing the `docker-compose` approach.
